name: ci
on: [push, pull_request]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COREPACK_ENABLE: 0
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
          run_install: false

      - name: Configure pnpm store
        run: |
          pnpm config set store-dir ~/.pnpm-store
          pnpm -v

      - name: Download PNPM store
        uses: actions/download-artifact@v4
        with: { name: pnpm-store, path: ./.cache-artifacts }

      - name: Hydrate PNPM store
        run: |
          STORE_DIR="$(pnpm store path)"
          mkdir -p "$STORE_DIR"
          tar -C "$STORE_DIR" -xzf ./.cache-artifacts/pnpm-store.tgz

      - name: Download Playwright cache
        uses: actions/download-artifact@v4
        with: { name: ms-playwright, path: ./.cache-artifacts }

      - name: Hydrate Playwright cache
        run: |
          mkdir -p ~/.cache/ms-playwright
          tar -C ~/.cache -xzf ./.cache-artifacts/ms-playwright.tgz

      - name: Offline install (no registry)
        env:
          PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright
        run: |
          pnpm install --offline
          pnpm --filter @agent-team/web install --offline

      - name: Build web
        run: pnpm web:build

      - name: Test web (unit)
        run: pnpm web:test

      - name: Test web (e2e, mocked)
        env:
          PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright
        run: pnpm web:e2e

      - name: Lint
        run: pnpm -w run lint

      - name: Typecheck
        run: pnpm -w run typecheck

      - name: Build
        run: pnpm -w run build

      - name: Tests (unit+pkg)
        run: pnpm run test:ci

      - name: E2E (mocked)
        env:
          GEMINI_API_KEY: ""
          CI_SKIP_REAL_GEMINI: "1"
        run: pnpm -w -r exec vitest --run apps/server/test/e2e/orch-ai-comm.e2e.test.ts

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: |
            packages/orchestration/coverage
            packages/ai/coverage
